### ISSUE TITLE
转图片显示不全，大多是在列表里面

### ISSUE THREAD

**Issue by ria-klee** [phquathi/nonebot_plugin_easymarkdown#1]
如图
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=3904128444836088962 skey=@crypt_d841e475_abc1be0ccea784ab0538dcbf22c5dc50 mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/76edc2f2-e5e8-49a2-b6ff-a0fd5a38774f)

**Comment by phquathi** [comment]
好的，问题还是出在手动换行那部分，字符再少一点应该就可以了

**Comment by phquathi** [comment]
明天修，这两天比较忙🙏

**Comment by phquathi** [comment]
之前实现主要是基于整个 HTML 的`<p>`标签进行换行处理，而列表项中的文本被包含在`<ul>`或`<li>`标签中，不是直接的`<p>`标签。这就导致在处理列表项时，没有添加适当的换行，目前已解决，更新插件即可
